steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/masahiko-project/supabase-test', '-f', 'Dockerfile.CloudRun', '.']
images:
- gcr.io/masahiko-project/supabase-test