FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /app
COPY ./src .

RUN dotnet publish -c Release -o dist

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime

WORKDIR /app
COPY --from=build /app/dist .

ENV TZ Asia/Tokyo
ENV ASPNETCORE_ENVIRONMENT Production

ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "SupabaseTest.dll"]
