name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Google Auth
      #   id: auth
      #   uses: 'google-github-actions/auth@v0'
      #   with:
      #     token_format: 'access_token'
      #     workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
      #     service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      # NOTE: Alternative option - authentication via credentials json
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Build and Push Container
        run: gcloud builds submit ./ --config cloudbuild.yml

      - name: Deploy to Cloud Run
        run: gcloud beta run deploy dotnet-test-api \
          --image gcr.io/masahiko-project/supabasetest \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --cpu-boost \
          --set-env-vars ConnectionStrings:DefaultConnection='${{ secrets.DOTNET_DEFAULT_CONNECTION }}'
